# syntax=docker/dockerfile:1.7
FROM golang:1.25
WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
	go build -o /bin/api ./cmd/api && \
	go build -o /bin/migrate ./cmd/migrate
CMD ["/bin/api"]
